Repository JoseAugustoJasfarias/soulpet-back, pull requests merged in 2023-05, with the labels that each got.

#45 Spt 6
  .env.exemple
  index.js
  morgan-mongoose.js
  package-lock.json
  package.json
Labels: documentation, enhancement

#46 BE-6
  routes/clientes.js
Labels: documentation, enhancement

#47 BE-9
  database/agendamento.js
  database/servico.js
Labels: documentation, enhancement

#48 BE-14
  index.js
  routes/agendamentos.js
Labels: documentation, enhancement

#50 Criação da rota de atualização de pedido por uuid
  .env.exemple
  database/produto.js
  package-lock.json
  package.json
  routes/clientes.js
  routes/pedidos.js
  routes/pets.js
  routes/produtos.js
  routes/servicos.js
Labels: documentation, enhancement

#52 Deletar pedidos
  package-lock.json
  package.json
  routes/pedidos.js
  routes/produtos.js
Labels: documentation, enhancement

#53 Correção de Rota
  routes/servicos.js
Labels: bug

#54 Task SPT#7 LucasDamasceno
  README.md
Labels: documentation, enhancement

#55 Criação da rota Put para atualizar o agendamento
  routes/agendamentos.js
  routes/pedidos.js
Labels: documentation, enhancement

#56 Rota para deletar Agendamento
  routes/agendamentos.js
Labels: documentation, enhancement

#57 Criação para gerar pdf dos clientes
  .env.exemple
  package-lock.json
  package.json
  routes/agendamentos.js
  routes/clientes.js
Labels: documentation, enhancement

#58 Ajuste id Pedido
  database/agendamento.js
  database/pedido.js
  routes/pedidos.js
Labels: documentation, enhancement

#59 Fixando Bugs de Rotas
  database/agendamento.js
  routes/agendamentos.js
Labels: bug, enhancement
